# Generated by Django 3.2 on 2021-05-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Subject',
            new_name='subject',
        ),
    ]
